import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google"
import "@/app/globals.css";
import {cn} from "@/lib/utils";
import {Sidebar} from "@/components/sidebar";
import {Breadcrumb} from "@/components/breadcrumb";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
    title: "Backoffice",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased",
                fontSans.variable
            )}
        >
        <div className="border-t bg-background">
            <div className="grid lg:grid-cols-5">
                <Sidebar className="hidden md:block" playlists={[]}/>
                <div className="h-full col-span-4 lg:border-l">
                    <div className=" px-4 py-6 lg:px-8">
                        <Breadcrumb/>

                        {children}
                    </div>
                </div>
            </div>
        </div>
        </body>
        </html>
    );
}
